apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: flr-filebeat
  name: flr-filebeat-cluster-role

rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: flr-filebeat
  name: flr-filebeat-cluster-role-binding

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flr-filebeat-cluster-role
subjects:
- kind: ServiceAccount
  name: flr-filebeat
  namespace: flr

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: flr-filebeat
  namespace: flr