---
apiVersion: v1
kind: Service
metadata:
  name: flr-logstash
  namespace: flr
spec:
  ports:
  - port: 5044
  selector:
    app: flr-logstash
  clusterIP: None

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flr-logstash
  namespace: flr
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: flr-logstash
  template:
    metadata:
      labels:
        app: flr-logstash
    spec:
      nodeSelector: 
        kubernetes.io/hostname: 10.10.10.61
      containers:
      - image: docker.elastic.co/logstash/logstash:7.3.2
        name: flr-logstash
        ports:
        - containerPort: 5044
          name: logstash
        resources:
          limits:
            cpu: 200m
            memory: 1280Mi
          requests:
            cpu: 200m
            memory: 1280Mi
            
        volumeMounts:
        - mountPath: /usr/share/logstash/pipeline/logstash.conf
          name: logstash-config
          subPath: logstash.conf
        - mountPath: /usr/share/logstash/config/logstash.yml
          name: logstashyml-config
          subPath: logstash.yml
        - mountPath: /data/logs/vems/
          name: flroutputlogdir
          

      volumes:
      - configMap:
          defaultMode: 0777
          name: flr-logstash-config
        name: logstash-config
      - configMap:
          defaultMode: 0777
          name: flr-logstashyml-config
        name: logstashyml-config
      - hostPath:
          path: /data/logs/vems/
          type: ""
        name: flroutputlogdir


